<?php

return [
    'battle-ready-laravel' => 'https://battle-ready-laravel.com/?aff=WJ9DG',
    'cloudways-php' => 'https://www.cloudways.com/en/php-hosting.php?id=1242932',
    'cloudways' => 'https://www.cloudways.com/en/laravel-hosting?id=1242932',
    'codecademy' => 'https://www.pjtra.com/t/2-438168-292025-213588',
    'consuming-apis-laravel' => 'https://consuming-apis-in-laravel.com/?aff=WJ9DG',
    'digitalocean-managed-databases' => 'https://digitalocean.pxf.io/c/3801334/1377288/15890',
    'digitalocean-managed-mysql-database' => 'https://digitalocean.pxf.io/baNjbB',
    'digitalocean' => 'https://digitalocean.pxf.io/c/3801334/1377286/15890',
    'domain-driven-laravel' => 'https://martinjoo.gumroad.com/l/ddd-laravel-premium?a=266251475',
    'fathom-analytics' => 'https://usefathom.com/ref/JTPOCN',
    'flare' => 'https://flareapp.io/?via=benjamincrozat',
    'headshotpro' => 'https://www.headshotpro.com/?via=benjamincrozat',
    'hostgator' => 'https://partners.hostgator.com/Py6kbX',
    'kinsta' => 'https://kinsta.com/application-hosting/?kaid=AEFAUTRRTINA',
    'level-up-tailwind-css' => 'https://shrutibalasa.gumroad.com/l/level-up-with-tailwind-css?a=266251475',
    'mailcoach' => 'https://mailcoach.app/?via=benjamincrozat',
    'mastering-laravel-validation-rules' => 'https://nocompromises.gumroad.com/l/laravel-validation?a=266251475',
    'microservices-laravel' => 'https://martinjoo.gumroad.com/l/microservices-with-laravel-premium?a=266251475',
    'namecheap' => 'https://namecheap.pxf.io/c/3801334/1712998/5618',
    'oh-dear' => 'https://ohdear.app/?via=benjamincrozat',
    'pirsch-analytics' => 'https://pirsch.io/ref/Z0E1Nqogb5',
    'ploi' => 'https://ploi.io/register?referrer=eJAat2H4YE45BjmIwzBl',
    'savvycal' => 'https://savvycal.com/?via=benjamincrozat',
    'semrush' => 'https://semrush.sjv.io/benjamincrozat',
    'serverless-laravel' => 'https://jackellis.gumroad.com/l/serverlesslaravel?a=266251475',
    'setapp' => 'https://setapp.sjv.io/c/3801334/344537/5114',
    'simple-analytics' => 'https://simpleanalytics.com/?referral=benjamincrozat',
    'skillshare' => 'https://skillshare.eqcm.net/rQWAbD',
    'tinkerwell' => 'https://tinkerwell.app/?ref=benjamincrozat',
    'tower' => 'https://www.git-tower.com/?via=benjamincrozat',
    'untitled-ui' => 'https://store.untitledui.com?aff=WJ9DG',
    'vue-design-patterns' => 'https://lachlanmiller.gumroad.com/l/vuejs-design-patterns?a=266251475',
    'vultr' => 'https://www.vultr.com/products/cloud-compute/?ref=9270910-8H',
    'webshare' => 'https://www.webshare.io/?referral_code=dt6d6ofk1rzp',
    'wincher' => 'https://www.wincher.com/rank-tracker?via=benjamincrozat',
];
